// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/plutolove233/co-dream/internal/dal/models"
)

func newAgentTask(db *gorm.DB, opts ...gen.DOOption) agentTask {
	_agentTask := agentTask{}

	_agentTask.agentTaskDo.UseDB(db, opts...)
	_agentTask.agentTaskDo.UseModel(&models.AgentTask{})

	tableName := _agentTask.agentTaskDo.TableName()
	_agentTask.ALL = field.NewAsterisk(tableName)
	_agentTask.ID = field.NewString(tableName, "id")
	_agentTask.UserID = field.NewString(tableName, "user_id")
	_agentTask.StageExecutionID = field.NewString(tableName, "stage_execution_id")
	_agentTask.AgentType = field.NewString(tableName, "agent_type")
	_agentTask.Status = field.NewString(tableName, "status")
	_agentTask.Input = field.NewString(tableName, "input")
	_agentTask.Output = field.NewString(tableName, "output")
	_agentTask.ModelConfig = field.NewString(tableName, "model_config")
	_agentTask.TokenUsage = field.NewString(tableName, "token_usage")
	_agentTask.IsDeleted = field.NewBool(tableName, "is_deleted")
	_agentTask.StartedAt = field.NewTime(tableName, "started_at")
	_agentTask.CompletedAt = field.NewTime(tableName, "completed_at")
	_agentTask.CreatedAt = field.NewTime(tableName, "created_at")
	_agentTask.UpdatedAt = field.NewTime(tableName, "updated_at")
	_agentTask.DeletedAt = field.NewField(tableName, "deleted_at")

	_agentTask.fillFieldMap()

	return _agentTask
}

type agentTask struct {
	agentTaskDo agentTaskDo

	ALL              field.Asterisk
	ID               field.String
	UserID           field.String
	StageExecutionID field.String
	AgentType        field.String
	Status           field.String
	Input            field.String
	Output           field.String
	ModelConfig      field.String
	TokenUsage       field.String
	IsDeleted        field.Bool
	StartedAt        field.Time
	CompletedAt      field.Time
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field

	fieldMap map[string]field.Expr
}

func (a agentTask) Table(newTableName string) *agentTask {
	a.agentTaskDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a agentTask) As(alias string) *agentTask {
	a.agentTaskDo.DO = *(a.agentTaskDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *agentTask) updateTableName(table string) *agentTask {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.UserID = field.NewString(table, "user_id")
	a.StageExecutionID = field.NewString(table, "stage_execution_id")
	a.AgentType = field.NewString(table, "agent_type")
	a.Status = field.NewString(table, "status")
	a.Input = field.NewString(table, "input")
	a.Output = field.NewString(table, "output")
	a.ModelConfig = field.NewString(table, "model_config")
	a.TokenUsage = field.NewString(table, "token_usage")
	a.IsDeleted = field.NewBool(table, "is_deleted")
	a.StartedAt = field.NewTime(table, "started_at")
	a.CompletedAt = field.NewTime(table, "completed_at")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")

	a.fillFieldMap()

	return a
}

func (a *agentTask) WithContext(ctx context.Context) IAgentTaskDo {
	return a.agentTaskDo.WithContext(ctx)
}

func (a agentTask) TableName() string { return a.agentTaskDo.TableName() }

func (a agentTask) Alias() string { return a.agentTaskDo.Alias() }

func (a agentTask) Columns(cols ...field.Expr) gen.Columns { return a.agentTaskDo.Columns(cols...) }

func (a *agentTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *agentTask) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 15)
	a.fieldMap["id"] = a.ID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["stage_execution_id"] = a.StageExecutionID
	a.fieldMap["agent_type"] = a.AgentType
	a.fieldMap["status"] = a.Status
	a.fieldMap["input"] = a.Input
	a.fieldMap["output"] = a.Output
	a.fieldMap["model_config"] = a.ModelConfig
	a.fieldMap["token_usage"] = a.TokenUsage
	a.fieldMap["is_deleted"] = a.IsDeleted
	a.fieldMap["started_at"] = a.StartedAt
	a.fieldMap["completed_at"] = a.CompletedAt
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
}

func (a agentTask) clone(db *gorm.DB) agentTask {
	a.agentTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a agentTask) replaceDB(db *gorm.DB) agentTask {
	a.agentTaskDo.ReplaceDB(db)
	return a
}

type agentTaskDo struct{ gen.DO }

type IAgentTaskDo interface {
	gen.SubQuery
	Debug() IAgentTaskDo
	WithContext(ctx context.Context) IAgentTaskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAgentTaskDo
	WriteDB() IAgentTaskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAgentTaskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAgentTaskDo
	Not(conds ...gen.Condition) IAgentTaskDo
	Or(conds ...gen.Condition) IAgentTaskDo
	Select(conds ...field.Expr) IAgentTaskDo
	Where(conds ...gen.Condition) IAgentTaskDo
	Order(conds ...field.Expr) IAgentTaskDo
	Distinct(cols ...field.Expr) IAgentTaskDo
	Omit(cols ...field.Expr) IAgentTaskDo
	Join(table schema.Tabler, on ...field.Expr) IAgentTaskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAgentTaskDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAgentTaskDo
	Group(cols ...field.Expr) IAgentTaskDo
	Having(conds ...gen.Condition) IAgentTaskDo
	Limit(limit int) IAgentTaskDo
	Offset(offset int) IAgentTaskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentTaskDo
	Unscoped() IAgentTaskDo
	Create(values ...*models.AgentTask) error
	CreateInBatches(values []*models.AgentTask, batchSize int) error
	Save(values ...*models.AgentTask) error
	First() (*models.AgentTask, error)
	Take() (*models.AgentTask, error)
	Last() (*models.AgentTask, error)
	Find() ([]*models.AgentTask, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AgentTask, err error)
	FindInBatches(result *[]*models.AgentTask, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.AgentTask) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAgentTaskDo
	Assign(attrs ...field.AssignExpr) IAgentTaskDo
	Joins(fields ...field.RelationField) IAgentTaskDo
	Preload(fields ...field.RelationField) IAgentTaskDo
	FirstOrInit() (*models.AgentTask, error)
	FirstOrCreate() (*models.AgentTask, error)
	FindByPage(offset int, limit int) (result []*models.AgentTask, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAgentTaskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a agentTaskDo) Debug() IAgentTaskDo {
	return a.withDO(a.DO.Debug())
}

func (a agentTaskDo) WithContext(ctx context.Context) IAgentTaskDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a agentTaskDo) ReadDB() IAgentTaskDo {
	return a.Clauses(dbresolver.Read)
}

func (a agentTaskDo) WriteDB() IAgentTaskDo {
	return a.Clauses(dbresolver.Write)
}

func (a agentTaskDo) Session(config *gorm.Session) IAgentTaskDo {
	return a.withDO(a.DO.Session(config))
}

func (a agentTaskDo) Clauses(conds ...clause.Expression) IAgentTaskDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a agentTaskDo) Returning(value interface{}, columns ...string) IAgentTaskDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a agentTaskDo) Not(conds ...gen.Condition) IAgentTaskDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a agentTaskDo) Or(conds ...gen.Condition) IAgentTaskDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a agentTaskDo) Select(conds ...field.Expr) IAgentTaskDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a agentTaskDo) Where(conds ...gen.Condition) IAgentTaskDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a agentTaskDo) Order(conds ...field.Expr) IAgentTaskDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a agentTaskDo) Distinct(cols ...field.Expr) IAgentTaskDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a agentTaskDo) Omit(cols ...field.Expr) IAgentTaskDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a agentTaskDo) Join(table schema.Tabler, on ...field.Expr) IAgentTaskDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a agentTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAgentTaskDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a agentTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) IAgentTaskDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a agentTaskDo) Group(cols ...field.Expr) IAgentTaskDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a agentTaskDo) Having(conds ...gen.Condition) IAgentTaskDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a agentTaskDo) Limit(limit int) IAgentTaskDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a agentTaskDo) Offset(offset int) IAgentTaskDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a agentTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAgentTaskDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a agentTaskDo) Unscoped() IAgentTaskDo {
	return a.withDO(a.DO.Unscoped())
}

func (a agentTaskDo) Create(values ...*models.AgentTask) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a agentTaskDo) CreateInBatches(values []*models.AgentTask, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a agentTaskDo) Save(values ...*models.AgentTask) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a agentTaskDo) First() (*models.AgentTask, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentTask), nil
	}
}

func (a agentTaskDo) Take() (*models.AgentTask, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentTask), nil
	}
}

func (a agentTaskDo) Last() (*models.AgentTask, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentTask), nil
	}
}

func (a agentTaskDo) Find() ([]*models.AgentTask, error) {
	result, err := a.DO.Find()
	return result.([]*models.AgentTask), err
}

func (a agentTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AgentTask, err error) {
	buf := make([]*models.AgentTask, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a agentTaskDo) FindInBatches(result *[]*models.AgentTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a agentTaskDo) Attrs(attrs ...field.AssignExpr) IAgentTaskDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a agentTaskDo) Assign(attrs ...field.AssignExpr) IAgentTaskDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a agentTaskDo) Joins(fields ...field.RelationField) IAgentTaskDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a agentTaskDo) Preload(fields ...field.RelationField) IAgentTaskDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a agentTaskDo) FirstOrInit() (*models.AgentTask, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentTask), nil
	}
}

func (a agentTaskDo) FirstOrCreate() (*models.AgentTask, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.AgentTask), nil
	}
}

func (a agentTaskDo) FindByPage(offset int, limit int) (result []*models.AgentTask, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a agentTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a agentTaskDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a agentTaskDo) Delete(models ...*models.AgentTask) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *agentTaskDo) withDO(do gen.Dao) *agentTaskDo {
	a.DO = *do.(*gen.DO)
	return a
}
