// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/plutolove233/co-dream/internal/dal/models"
)

func newCheckpoint(db *gorm.DB, opts ...gen.DOOption) checkpoint {
	_checkpoint := checkpoint{}

	_checkpoint.checkpointDo.UseDB(db, opts...)
	_checkpoint.checkpointDo.UseModel(&models.Checkpoint{})

	tableName := _checkpoint.checkpointDo.TableName()
	_checkpoint.ALL = field.NewAsterisk(tableName)
	_checkpoint.ID = field.NewString(tableName, "id")
	_checkpoint.UserID = field.NewString(tableName, "user_id")
	_checkpoint.ExecutionID = field.NewString(tableName, "execution_id")
	_checkpoint.StageID = field.NewString(tableName, "stage_id")
	_checkpoint.Position = field.NewString(tableName, "position")
	_checkpoint.Status = field.NewString(tableName, "status")
	_checkpoint.Artifacts = field.NewString(tableName, "artifacts")
	_checkpoint.Decision = field.NewString(tableName, "decision")
	_checkpoint.IsDeleted = field.NewBool(tableName, "is_deleted")
	_checkpoint.CreatedAt = field.NewTime(tableName, "created_at")
	_checkpoint.DecidedAt = field.NewTime(tableName, "decided_at")
	_checkpoint.DeletedAt = field.NewField(tableName, "deleted_at")

	_checkpoint.fillFieldMap()

	return _checkpoint
}

type checkpoint struct {
	checkpointDo checkpointDo

	ALL         field.Asterisk
	ID          field.String
	UserID      field.String
	ExecutionID field.String
	StageID     field.String
	Position    field.String
	Status      field.String
	Artifacts   field.String
	Decision    field.String
	IsDeleted   field.Bool
	CreatedAt   field.Time
	DecidedAt   field.Time
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (c checkpoint) Table(newTableName string) *checkpoint {
	c.checkpointDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c checkpoint) As(alias string) *checkpoint {
	c.checkpointDo.DO = *(c.checkpointDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *checkpoint) updateTableName(table string) *checkpoint {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.UserID = field.NewString(table, "user_id")
	c.ExecutionID = field.NewString(table, "execution_id")
	c.StageID = field.NewString(table, "stage_id")
	c.Position = field.NewString(table, "position")
	c.Status = field.NewString(table, "status")
	c.Artifacts = field.NewString(table, "artifacts")
	c.Decision = field.NewString(table, "decision")
	c.IsDeleted = field.NewBool(table, "is_deleted")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.DecidedAt = field.NewTime(table, "decided_at")
	c.DeletedAt = field.NewField(table, "deleted_at")

	c.fillFieldMap()

	return c
}

func (c *checkpoint) WithContext(ctx context.Context) ICheckpointDo {
	return c.checkpointDo.WithContext(ctx)
}

func (c checkpoint) TableName() string { return c.checkpointDo.TableName() }

func (c checkpoint) Alias() string { return c.checkpointDo.Alias() }

func (c checkpoint) Columns(cols ...field.Expr) gen.Columns { return c.checkpointDo.Columns(cols...) }

func (c *checkpoint) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *checkpoint) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 12)
	c.fieldMap["id"] = c.ID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["execution_id"] = c.ExecutionID
	c.fieldMap["stage_id"] = c.StageID
	c.fieldMap["position"] = c.Position
	c.fieldMap["status"] = c.Status
	c.fieldMap["artifacts"] = c.Artifacts
	c.fieldMap["decision"] = c.Decision
	c.fieldMap["is_deleted"] = c.IsDeleted
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["decided_at"] = c.DecidedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
}

func (c checkpoint) clone(db *gorm.DB) checkpoint {
	c.checkpointDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c checkpoint) replaceDB(db *gorm.DB) checkpoint {
	c.checkpointDo.ReplaceDB(db)
	return c
}

type checkpointDo struct{ gen.DO }

type ICheckpointDo interface {
	gen.SubQuery
	Debug() ICheckpointDo
	WithContext(ctx context.Context) ICheckpointDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICheckpointDo
	WriteDB() ICheckpointDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICheckpointDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICheckpointDo
	Not(conds ...gen.Condition) ICheckpointDo
	Or(conds ...gen.Condition) ICheckpointDo
	Select(conds ...field.Expr) ICheckpointDo
	Where(conds ...gen.Condition) ICheckpointDo
	Order(conds ...field.Expr) ICheckpointDo
	Distinct(cols ...field.Expr) ICheckpointDo
	Omit(cols ...field.Expr) ICheckpointDo
	Join(table schema.Tabler, on ...field.Expr) ICheckpointDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICheckpointDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICheckpointDo
	Group(cols ...field.Expr) ICheckpointDo
	Having(conds ...gen.Condition) ICheckpointDo
	Limit(limit int) ICheckpointDo
	Offset(offset int) ICheckpointDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICheckpointDo
	Unscoped() ICheckpointDo
	Create(values ...*models.Checkpoint) error
	CreateInBatches(values []*models.Checkpoint, batchSize int) error
	Save(values ...*models.Checkpoint) error
	First() (*models.Checkpoint, error)
	Take() (*models.Checkpoint, error)
	Last() (*models.Checkpoint, error)
	Find() ([]*models.Checkpoint, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Checkpoint, err error)
	FindInBatches(result *[]*models.Checkpoint, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Checkpoint) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICheckpointDo
	Assign(attrs ...field.AssignExpr) ICheckpointDo
	Joins(fields ...field.RelationField) ICheckpointDo
	Preload(fields ...field.RelationField) ICheckpointDo
	FirstOrInit() (*models.Checkpoint, error)
	FirstOrCreate() (*models.Checkpoint, error)
	FindByPage(offset int, limit int) (result []*models.Checkpoint, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICheckpointDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c checkpointDo) Debug() ICheckpointDo {
	return c.withDO(c.DO.Debug())
}

func (c checkpointDo) WithContext(ctx context.Context) ICheckpointDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c checkpointDo) ReadDB() ICheckpointDo {
	return c.Clauses(dbresolver.Read)
}

func (c checkpointDo) WriteDB() ICheckpointDo {
	return c.Clauses(dbresolver.Write)
}

func (c checkpointDo) Session(config *gorm.Session) ICheckpointDo {
	return c.withDO(c.DO.Session(config))
}

func (c checkpointDo) Clauses(conds ...clause.Expression) ICheckpointDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c checkpointDo) Returning(value interface{}, columns ...string) ICheckpointDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c checkpointDo) Not(conds ...gen.Condition) ICheckpointDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c checkpointDo) Or(conds ...gen.Condition) ICheckpointDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c checkpointDo) Select(conds ...field.Expr) ICheckpointDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c checkpointDo) Where(conds ...gen.Condition) ICheckpointDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c checkpointDo) Order(conds ...field.Expr) ICheckpointDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c checkpointDo) Distinct(cols ...field.Expr) ICheckpointDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c checkpointDo) Omit(cols ...field.Expr) ICheckpointDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c checkpointDo) Join(table schema.Tabler, on ...field.Expr) ICheckpointDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c checkpointDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICheckpointDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c checkpointDo) RightJoin(table schema.Tabler, on ...field.Expr) ICheckpointDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c checkpointDo) Group(cols ...field.Expr) ICheckpointDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c checkpointDo) Having(conds ...gen.Condition) ICheckpointDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c checkpointDo) Limit(limit int) ICheckpointDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c checkpointDo) Offset(offset int) ICheckpointDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c checkpointDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICheckpointDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c checkpointDo) Unscoped() ICheckpointDo {
	return c.withDO(c.DO.Unscoped())
}

func (c checkpointDo) Create(values ...*models.Checkpoint) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c checkpointDo) CreateInBatches(values []*models.Checkpoint, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c checkpointDo) Save(values ...*models.Checkpoint) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c checkpointDo) First() (*models.Checkpoint, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Checkpoint), nil
	}
}

func (c checkpointDo) Take() (*models.Checkpoint, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Checkpoint), nil
	}
}

func (c checkpointDo) Last() (*models.Checkpoint, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Checkpoint), nil
	}
}

func (c checkpointDo) Find() ([]*models.Checkpoint, error) {
	result, err := c.DO.Find()
	return result.([]*models.Checkpoint), err
}

func (c checkpointDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Checkpoint, err error) {
	buf := make([]*models.Checkpoint, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c checkpointDo) FindInBatches(result *[]*models.Checkpoint, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c checkpointDo) Attrs(attrs ...field.AssignExpr) ICheckpointDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c checkpointDo) Assign(attrs ...field.AssignExpr) ICheckpointDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c checkpointDo) Joins(fields ...field.RelationField) ICheckpointDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c checkpointDo) Preload(fields ...field.RelationField) ICheckpointDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c checkpointDo) FirstOrInit() (*models.Checkpoint, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Checkpoint), nil
	}
}

func (c checkpointDo) FirstOrCreate() (*models.Checkpoint, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Checkpoint), nil
	}
}

func (c checkpointDo) FindByPage(offset int, limit int) (result []*models.Checkpoint, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c checkpointDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c checkpointDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c checkpointDo) Delete(models ...*models.Checkpoint) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *checkpointDo) withDO(do gen.Dao) *checkpointDo {
	c.DO = *do.(*gen.DO)
	return c
}
