// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	AgentTask         *agentTask
	Checkpoint        *checkpoint
	Message           *message
	Pipeline          *pipeline
	PipelineExecution *pipelineExecution
	Session           *session
	StageExecution    *stageExecution
	User              *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AgentTask = &Q.AgentTask
	Checkpoint = &Q.Checkpoint
	Message = &Q.Message
	Pipeline = &Q.Pipeline
	PipelineExecution = &Q.PipelineExecution
	Session = &Q.Session
	StageExecution = &Q.StageExecution
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		AgentTask:         newAgentTask(db, opts...),
		Checkpoint:        newCheckpoint(db, opts...),
		Message:           newMessage(db, opts...),
		Pipeline:          newPipeline(db, opts...),
		PipelineExecution: newPipelineExecution(db, opts...),
		Session:           newSession(db, opts...),
		StageExecution:    newStageExecution(db, opts...),
		User:              newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AgentTask         agentTask
	Checkpoint        checkpoint
	Message           message
	Pipeline          pipeline
	PipelineExecution pipelineExecution
	Session           session
	StageExecution    stageExecution
	User              user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		AgentTask:         q.AgentTask.clone(db),
		Checkpoint:        q.Checkpoint.clone(db),
		Message:           q.Message.clone(db),
		Pipeline:          q.Pipeline.clone(db),
		PipelineExecution: q.PipelineExecution.clone(db),
		Session:           q.Session.clone(db),
		StageExecution:    q.StageExecution.clone(db),
		User:              q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		AgentTask:         q.AgentTask.replaceDB(db),
		Checkpoint:        q.Checkpoint.replaceDB(db),
		Message:           q.Message.replaceDB(db),
		Pipeline:          q.Pipeline.replaceDB(db),
		PipelineExecution: q.PipelineExecution.replaceDB(db),
		Session:           q.Session.replaceDB(db),
		StageExecution:    q.StageExecution.replaceDB(db),
		User:              q.User.replaceDB(db),
	}
}

type queryCtx struct {
	AgentTask         IAgentTaskDo
	Checkpoint        ICheckpointDo
	Message           IMessageDo
	Pipeline          IPipelineDo
	PipelineExecution IPipelineExecutionDo
	Session           ISessionDo
	StageExecution    IStageExecutionDo
	User              IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AgentTask:         q.AgentTask.WithContext(ctx),
		Checkpoint:        q.Checkpoint.WithContext(ctx),
		Message:           q.Message.WithContext(ctx),
		Pipeline:          q.Pipeline.WithContext(ctx),
		PipelineExecution: q.PipelineExecution.WithContext(ctx),
		Session:           q.Session.WithContext(ctx),
		StageExecution:    q.StageExecution.WithContext(ctx),
		User:              q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
