// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/plutolove233/co-dream/internal/dal/models"
)

func newPipelineExecution(db *gorm.DB, opts ...gen.DOOption) pipelineExecution {
	_pipelineExecution := pipelineExecution{}

	_pipelineExecution.pipelineExecutionDo.UseDB(db, opts...)
	_pipelineExecution.pipelineExecutionDo.UseModel(&models.PipelineExecution{})

	tableName := _pipelineExecution.pipelineExecutionDo.TableName()
	_pipelineExecution.ALL = field.NewAsterisk(tableName)
	_pipelineExecution.ID = field.NewString(tableName, "id")
	_pipelineExecution.UserID = field.NewString(tableName, "user_id")
	_pipelineExecution.PipelineID = field.NewString(tableName, "pipeline_id")
	_pipelineExecution.Status = field.NewString(tableName, "status")
	_pipelineExecution.CurrentStageIndex = field.NewInt32(tableName, "current_stage_index")
	_pipelineExecution.Input = field.NewString(tableName, "input")
	_pipelineExecution.Output = field.NewString(tableName, "output")
	_pipelineExecution.IsDeleted = field.NewBool(tableName, "is_deleted")
	_pipelineExecution.StartedAt = field.NewTime(tableName, "started_at")
	_pipelineExecution.CompletedAt = field.NewTime(tableName, "completed_at")
	_pipelineExecution.CreatedAt = field.NewTime(tableName, "created_at")
	_pipelineExecution.UpdatedAt = field.NewTime(tableName, "updated_at")
	_pipelineExecution.DeletedAt = field.NewField(tableName, "deleted_at")

	_pipelineExecution.fillFieldMap()

	return _pipelineExecution
}

type pipelineExecution struct {
	pipelineExecutionDo pipelineExecutionDo

	ALL               field.Asterisk
	ID                field.String
	UserID            field.String
	PipelineID        field.String
	Status            field.String
	CurrentStageIndex field.Int32
	Input             field.String
	Output            field.String
	IsDeleted         field.Bool
	StartedAt         field.Time
	CompletedAt       field.Time
	CreatedAt         field.Time
	UpdatedAt         field.Time
	DeletedAt         field.Field

	fieldMap map[string]field.Expr
}

func (p pipelineExecution) Table(newTableName string) *pipelineExecution {
	p.pipelineExecutionDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p pipelineExecution) As(alias string) *pipelineExecution {
	p.pipelineExecutionDo.DO = *(p.pipelineExecutionDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *pipelineExecution) updateTableName(table string) *pipelineExecution {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewString(table, "id")
	p.UserID = field.NewString(table, "user_id")
	p.PipelineID = field.NewString(table, "pipeline_id")
	p.Status = field.NewString(table, "status")
	p.CurrentStageIndex = field.NewInt32(table, "current_stage_index")
	p.Input = field.NewString(table, "input")
	p.Output = field.NewString(table, "output")
	p.IsDeleted = field.NewBool(table, "is_deleted")
	p.StartedAt = field.NewTime(table, "started_at")
	p.CompletedAt = field.NewTime(table, "completed_at")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")

	p.fillFieldMap()

	return p
}

func (p *pipelineExecution) WithContext(ctx context.Context) IPipelineExecutionDo {
	return p.pipelineExecutionDo.WithContext(ctx)
}

func (p pipelineExecution) TableName() string { return p.pipelineExecutionDo.TableName() }

func (p pipelineExecution) Alias() string { return p.pipelineExecutionDo.Alias() }

func (p pipelineExecution) Columns(cols ...field.Expr) gen.Columns {
	return p.pipelineExecutionDo.Columns(cols...)
}

func (p *pipelineExecution) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *pipelineExecution) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 13)
	p.fieldMap["id"] = p.ID
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["pipeline_id"] = p.PipelineID
	p.fieldMap["status"] = p.Status
	p.fieldMap["current_stage_index"] = p.CurrentStageIndex
	p.fieldMap["input"] = p.Input
	p.fieldMap["output"] = p.Output
	p.fieldMap["is_deleted"] = p.IsDeleted
	p.fieldMap["started_at"] = p.StartedAt
	p.fieldMap["completed_at"] = p.CompletedAt
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
}

func (p pipelineExecution) clone(db *gorm.DB) pipelineExecution {
	p.pipelineExecutionDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p pipelineExecution) replaceDB(db *gorm.DB) pipelineExecution {
	p.pipelineExecutionDo.ReplaceDB(db)
	return p
}

type pipelineExecutionDo struct{ gen.DO }

type IPipelineExecutionDo interface {
	gen.SubQuery
	Debug() IPipelineExecutionDo
	WithContext(ctx context.Context) IPipelineExecutionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPipelineExecutionDo
	WriteDB() IPipelineExecutionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPipelineExecutionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPipelineExecutionDo
	Not(conds ...gen.Condition) IPipelineExecutionDo
	Or(conds ...gen.Condition) IPipelineExecutionDo
	Select(conds ...field.Expr) IPipelineExecutionDo
	Where(conds ...gen.Condition) IPipelineExecutionDo
	Order(conds ...field.Expr) IPipelineExecutionDo
	Distinct(cols ...field.Expr) IPipelineExecutionDo
	Omit(cols ...field.Expr) IPipelineExecutionDo
	Join(table schema.Tabler, on ...field.Expr) IPipelineExecutionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPipelineExecutionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPipelineExecutionDo
	Group(cols ...field.Expr) IPipelineExecutionDo
	Having(conds ...gen.Condition) IPipelineExecutionDo
	Limit(limit int) IPipelineExecutionDo
	Offset(offset int) IPipelineExecutionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPipelineExecutionDo
	Unscoped() IPipelineExecutionDo
	Create(values ...*models.PipelineExecution) error
	CreateInBatches(values []*models.PipelineExecution, batchSize int) error
	Save(values ...*models.PipelineExecution) error
	First() (*models.PipelineExecution, error)
	Take() (*models.PipelineExecution, error)
	Last() (*models.PipelineExecution, error)
	Find() ([]*models.PipelineExecution, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.PipelineExecution, err error)
	FindInBatches(result *[]*models.PipelineExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.PipelineExecution) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPipelineExecutionDo
	Assign(attrs ...field.AssignExpr) IPipelineExecutionDo
	Joins(fields ...field.RelationField) IPipelineExecutionDo
	Preload(fields ...field.RelationField) IPipelineExecutionDo
	FirstOrInit() (*models.PipelineExecution, error)
	FirstOrCreate() (*models.PipelineExecution, error)
	FindByPage(offset int, limit int) (result []*models.PipelineExecution, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPipelineExecutionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p pipelineExecutionDo) Debug() IPipelineExecutionDo {
	return p.withDO(p.DO.Debug())
}

func (p pipelineExecutionDo) WithContext(ctx context.Context) IPipelineExecutionDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p pipelineExecutionDo) ReadDB() IPipelineExecutionDo {
	return p.Clauses(dbresolver.Read)
}

func (p pipelineExecutionDo) WriteDB() IPipelineExecutionDo {
	return p.Clauses(dbresolver.Write)
}

func (p pipelineExecutionDo) Session(config *gorm.Session) IPipelineExecutionDo {
	return p.withDO(p.DO.Session(config))
}

func (p pipelineExecutionDo) Clauses(conds ...clause.Expression) IPipelineExecutionDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p pipelineExecutionDo) Returning(value interface{}, columns ...string) IPipelineExecutionDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p pipelineExecutionDo) Not(conds ...gen.Condition) IPipelineExecutionDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p pipelineExecutionDo) Or(conds ...gen.Condition) IPipelineExecutionDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p pipelineExecutionDo) Select(conds ...field.Expr) IPipelineExecutionDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p pipelineExecutionDo) Where(conds ...gen.Condition) IPipelineExecutionDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p pipelineExecutionDo) Order(conds ...field.Expr) IPipelineExecutionDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p pipelineExecutionDo) Distinct(cols ...field.Expr) IPipelineExecutionDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p pipelineExecutionDo) Omit(cols ...field.Expr) IPipelineExecutionDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p pipelineExecutionDo) Join(table schema.Tabler, on ...field.Expr) IPipelineExecutionDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p pipelineExecutionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPipelineExecutionDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p pipelineExecutionDo) RightJoin(table schema.Tabler, on ...field.Expr) IPipelineExecutionDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p pipelineExecutionDo) Group(cols ...field.Expr) IPipelineExecutionDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p pipelineExecutionDo) Having(conds ...gen.Condition) IPipelineExecutionDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p pipelineExecutionDo) Limit(limit int) IPipelineExecutionDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p pipelineExecutionDo) Offset(offset int) IPipelineExecutionDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p pipelineExecutionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPipelineExecutionDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p pipelineExecutionDo) Unscoped() IPipelineExecutionDo {
	return p.withDO(p.DO.Unscoped())
}

func (p pipelineExecutionDo) Create(values ...*models.PipelineExecution) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p pipelineExecutionDo) CreateInBatches(values []*models.PipelineExecution, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p pipelineExecutionDo) Save(values ...*models.PipelineExecution) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p pipelineExecutionDo) First() (*models.PipelineExecution, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.PipelineExecution), nil
	}
}

func (p pipelineExecutionDo) Take() (*models.PipelineExecution, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.PipelineExecution), nil
	}
}

func (p pipelineExecutionDo) Last() (*models.PipelineExecution, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.PipelineExecution), nil
	}
}

func (p pipelineExecutionDo) Find() ([]*models.PipelineExecution, error) {
	result, err := p.DO.Find()
	return result.([]*models.PipelineExecution), err
}

func (p pipelineExecutionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.PipelineExecution, err error) {
	buf := make([]*models.PipelineExecution, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p pipelineExecutionDo) FindInBatches(result *[]*models.PipelineExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p pipelineExecutionDo) Attrs(attrs ...field.AssignExpr) IPipelineExecutionDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p pipelineExecutionDo) Assign(attrs ...field.AssignExpr) IPipelineExecutionDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p pipelineExecutionDo) Joins(fields ...field.RelationField) IPipelineExecutionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p pipelineExecutionDo) Preload(fields ...field.RelationField) IPipelineExecutionDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p pipelineExecutionDo) FirstOrInit() (*models.PipelineExecution, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.PipelineExecution), nil
	}
}

func (p pipelineExecutionDo) FirstOrCreate() (*models.PipelineExecution, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.PipelineExecution), nil
	}
}

func (p pipelineExecutionDo) FindByPage(offset int, limit int) (result []*models.PipelineExecution, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p pipelineExecutionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p pipelineExecutionDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p pipelineExecutionDo) Delete(models ...*models.PipelineExecution) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *pipelineExecutionDo) withDO(do gen.Dao) *pipelineExecutionDo {
	p.DO = *do.(*gen.DO)
	return p
}
