// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/plutolove233/co-dream/internal/dal/models"
)

func newStageExecution(db *gorm.DB, opts ...gen.DOOption) stageExecution {
	_stageExecution := stageExecution{}

	_stageExecution.stageExecutionDo.UseDB(db, opts...)
	_stageExecution.stageExecutionDo.UseModel(&models.StageExecution{})

	tableName := _stageExecution.stageExecutionDo.TableName()
	_stageExecution.ALL = field.NewAsterisk(tableName)
	_stageExecution.ID = field.NewString(tableName, "id")
	_stageExecution.UserID = field.NewString(tableName, "user_id")
	_stageExecution.ExecutionID = field.NewString(tableName, "execution_id")
	_stageExecution.StageName = field.NewString(tableName, "stage_name")
	_stageExecution.StageOrder = field.NewInt32(tableName, "stage_order")
	_stageExecution.Status = field.NewString(tableName, "status")
	_stageExecution.Input = field.NewString(tableName, "input")
	_stageExecution.Output = field.NewString(tableName, "output")
	_stageExecution.Plan = field.NewString(tableName, "plan")
	_stageExecution.RetryCount = field.NewInt32(tableName, "retry_count")
	_stageExecution.IsDeleted = field.NewBool(tableName, "is_deleted")
	_stageExecution.StartedAt = field.NewTime(tableName, "started_at")
	_stageExecution.CompletedAt = field.NewTime(tableName, "completed_at")
	_stageExecution.CreatedAt = field.NewTime(tableName, "created_at")
	_stageExecution.UpdatedAt = field.NewTime(tableName, "updated_at")
	_stageExecution.DeletedAt = field.NewField(tableName, "deleted_at")

	_stageExecution.fillFieldMap()

	return _stageExecution
}

type stageExecution struct {
	stageExecutionDo stageExecutionDo

	ALL         field.Asterisk
	ID          field.String
	UserID      field.String
	ExecutionID field.String
	StageName   field.String
	StageOrder  field.Int32
	Status      field.String
	Input       field.String
	Output      field.String
	Plan        field.String
	RetryCount  field.Int32
	IsDeleted   field.Bool
	StartedAt   field.Time
	CompletedAt field.Time
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (s stageExecution) Table(newTableName string) *stageExecution {
	s.stageExecutionDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s stageExecution) As(alias string) *stageExecution {
	s.stageExecutionDo.DO = *(s.stageExecutionDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *stageExecution) updateTableName(table string) *stageExecution {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewString(table, "id")
	s.UserID = field.NewString(table, "user_id")
	s.ExecutionID = field.NewString(table, "execution_id")
	s.StageName = field.NewString(table, "stage_name")
	s.StageOrder = field.NewInt32(table, "stage_order")
	s.Status = field.NewString(table, "status")
	s.Input = field.NewString(table, "input")
	s.Output = field.NewString(table, "output")
	s.Plan = field.NewString(table, "plan")
	s.RetryCount = field.NewInt32(table, "retry_count")
	s.IsDeleted = field.NewBool(table, "is_deleted")
	s.StartedAt = field.NewTime(table, "started_at")
	s.CompletedAt = field.NewTime(table, "completed_at")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *stageExecution) WithContext(ctx context.Context) IStageExecutionDo {
	return s.stageExecutionDo.WithContext(ctx)
}

func (s stageExecution) TableName() string { return s.stageExecutionDo.TableName() }

func (s stageExecution) Alias() string { return s.stageExecutionDo.Alias() }

func (s stageExecution) Columns(cols ...field.Expr) gen.Columns {
	return s.stageExecutionDo.Columns(cols...)
}

func (s *stageExecution) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *stageExecution) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 16)
	s.fieldMap["id"] = s.ID
	s.fieldMap["user_id"] = s.UserID
	s.fieldMap["execution_id"] = s.ExecutionID
	s.fieldMap["stage_name"] = s.StageName
	s.fieldMap["stage_order"] = s.StageOrder
	s.fieldMap["status"] = s.Status
	s.fieldMap["input"] = s.Input
	s.fieldMap["output"] = s.Output
	s.fieldMap["plan"] = s.Plan
	s.fieldMap["retry_count"] = s.RetryCount
	s.fieldMap["is_deleted"] = s.IsDeleted
	s.fieldMap["started_at"] = s.StartedAt
	s.fieldMap["completed_at"] = s.CompletedAt
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s stageExecution) clone(db *gorm.DB) stageExecution {
	s.stageExecutionDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s stageExecution) replaceDB(db *gorm.DB) stageExecution {
	s.stageExecutionDo.ReplaceDB(db)
	return s
}

type stageExecutionDo struct{ gen.DO }

type IStageExecutionDo interface {
	gen.SubQuery
	Debug() IStageExecutionDo
	WithContext(ctx context.Context) IStageExecutionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStageExecutionDo
	WriteDB() IStageExecutionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStageExecutionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStageExecutionDo
	Not(conds ...gen.Condition) IStageExecutionDo
	Or(conds ...gen.Condition) IStageExecutionDo
	Select(conds ...field.Expr) IStageExecutionDo
	Where(conds ...gen.Condition) IStageExecutionDo
	Order(conds ...field.Expr) IStageExecutionDo
	Distinct(cols ...field.Expr) IStageExecutionDo
	Omit(cols ...field.Expr) IStageExecutionDo
	Join(table schema.Tabler, on ...field.Expr) IStageExecutionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStageExecutionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStageExecutionDo
	Group(cols ...field.Expr) IStageExecutionDo
	Having(conds ...gen.Condition) IStageExecutionDo
	Limit(limit int) IStageExecutionDo
	Offset(offset int) IStageExecutionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStageExecutionDo
	Unscoped() IStageExecutionDo
	Create(values ...*models.StageExecution) error
	CreateInBatches(values []*models.StageExecution, batchSize int) error
	Save(values ...*models.StageExecution) error
	First() (*models.StageExecution, error)
	Take() (*models.StageExecution, error)
	Last() (*models.StageExecution, error)
	Find() ([]*models.StageExecution, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.StageExecution, err error)
	FindInBatches(result *[]*models.StageExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.StageExecution) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStageExecutionDo
	Assign(attrs ...field.AssignExpr) IStageExecutionDo
	Joins(fields ...field.RelationField) IStageExecutionDo
	Preload(fields ...field.RelationField) IStageExecutionDo
	FirstOrInit() (*models.StageExecution, error)
	FirstOrCreate() (*models.StageExecution, error)
	FindByPage(offset int, limit int) (result []*models.StageExecution, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStageExecutionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s stageExecutionDo) Debug() IStageExecutionDo {
	return s.withDO(s.DO.Debug())
}

func (s stageExecutionDo) WithContext(ctx context.Context) IStageExecutionDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s stageExecutionDo) ReadDB() IStageExecutionDo {
	return s.Clauses(dbresolver.Read)
}

func (s stageExecutionDo) WriteDB() IStageExecutionDo {
	return s.Clauses(dbresolver.Write)
}

func (s stageExecutionDo) Session(config *gorm.Session) IStageExecutionDo {
	return s.withDO(s.DO.Session(config))
}

func (s stageExecutionDo) Clauses(conds ...clause.Expression) IStageExecutionDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s stageExecutionDo) Returning(value interface{}, columns ...string) IStageExecutionDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s stageExecutionDo) Not(conds ...gen.Condition) IStageExecutionDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s stageExecutionDo) Or(conds ...gen.Condition) IStageExecutionDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s stageExecutionDo) Select(conds ...field.Expr) IStageExecutionDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s stageExecutionDo) Where(conds ...gen.Condition) IStageExecutionDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s stageExecutionDo) Order(conds ...field.Expr) IStageExecutionDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s stageExecutionDo) Distinct(cols ...field.Expr) IStageExecutionDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s stageExecutionDo) Omit(cols ...field.Expr) IStageExecutionDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s stageExecutionDo) Join(table schema.Tabler, on ...field.Expr) IStageExecutionDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s stageExecutionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStageExecutionDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s stageExecutionDo) RightJoin(table schema.Tabler, on ...field.Expr) IStageExecutionDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s stageExecutionDo) Group(cols ...field.Expr) IStageExecutionDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s stageExecutionDo) Having(conds ...gen.Condition) IStageExecutionDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s stageExecutionDo) Limit(limit int) IStageExecutionDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s stageExecutionDo) Offset(offset int) IStageExecutionDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s stageExecutionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStageExecutionDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s stageExecutionDo) Unscoped() IStageExecutionDo {
	return s.withDO(s.DO.Unscoped())
}

func (s stageExecutionDo) Create(values ...*models.StageExecution) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s stageExecutionDo) CreateInBatches(values []*models.StageExecution, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s stageExecutionDo) Save(values ...*models.StageExecution) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s stageExecutionDo) First() (*models.StageExecution, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.StageExecution), nil
	}
}

func (s stageExecutionDo) Take() (*models.StageExecution, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.StageExecution), nil
	}
}

func (s stageExecutionDo) Last() (*models.StageExecution, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.StageExecution), nil
	}
}

func (s stageExecutionDo) Find() ([]*models.StageExecution, error) {
	result, err := s.DO.Find()
	return result.([]*models.StageExecution), err
}

func (s stageExecutionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.StageExecution, err error) {
	buf := make([]*models.StageExecution, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s stageExecutionDo) FindInBatches(result *[]*models.StageExecution, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s stageExecutionDo) Attrs(attrs ...field.AssignExpr) IStageExecutionDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s stageExecutionDo) Assign(attrs ...field.AssignExpr) IStageExecutionDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s stageExecutionDo) Joins(fields ...field.RelationField) IStageExecutionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s stageExecutionDo) Preload(fields ...field.RelationField) IStageExecutionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s stageExecutionDo) FirstOrInit() (*models.StageExecution, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.StageExecution), nil
	}
}

func (s stageExecutionDo) FirstOrCreate() (*models.StageExecution, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.StageExecution), nil
	}
}

func (s stageExecutionDo) FindByPage(offset int, limit int) (result []*models.StageExecution, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s stageExecutionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s stageExecutionDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s stageExecutionDo) Delete(models ...*models.StageExecution) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *stageExecutionDo) withDO(do gen.Dao) *stageExecutionDo {
	s.DO = *do.(*gen.DO)
	return s
}
