// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMessage = "messages"

// Message mapped from table <messages>
type Message struct {
	ID           *string        `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID       string         `gorm:"column:user_id;type:uuid;not null;index:idx_messages_user_id,priority:1;index:idx_messages_user_is_deleted,priority:1" json:"user_id"`
	SessionID    string         `gorm:"column:session_id;type:uuid;not null;index:idx_messages_session_order,priority:1;index:idx_messages_session_id,priority:1" json:"session_id"`
	Role         string         `gorm:"column:role;type:character varying(50);not null;index:idx_messages_role,priority:1" json:"role"`
	MessageOrder int32          `gorm:"column:message_order;type:integer;not null;index:idx_messages_session_order,priority:2" json:"message_order"`
	Content      string         `gorm:"column:content;type:text;not null" json:"content"`
	ToolCalls    *string        `gorm:"column:tool_calls;type:jsonb;not null;default:[]" json:"tool_calls"`
	TokenUsage   *string        `gorm:"column:token_usage;type:jsonb;not null;default:{}" json:"token_usage"`
	Model        *string        `gorm:"column:model;type:character varying(255)" json:"model"`
	FinishReason *string        `gorm:"column:finish_reason;type:character varying(100)" json:"finish_reason"`
	Status       *string        `gorm:"column:status;type:character varying(50);not null;index:idx_messages_status,priority:1;default:completed" json:"status"`
	Metadata     *string        `gorm:"column:metadata;type:jsonb;not null;default:{}" json:"metadata"`
	IsDeleted    bool           `gorm:"column:is_deleted;type:boolean;not null;index:idx_messages_is_deleted,priority:1;index:idx_messages_user_is_deleted,priority:2" json:"is_deleted"`
	CreatedAt    *time.Time     `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_messages_created_at,priority:1;default:now()" json:"created_at"`
	UpdatedAt    *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index:idx_messages_deleted_at,priority:1" json:"deleted_at"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
