// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePipelineExecution = "pipeline_executions"

// PipelineExecution mapped from table <pipeline_executions>
type PipelineExecution struct {
	ID                *string        `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID            string         `gorm:"column:user_id;type:uuid;not null;index:idx_pipeline_executions_user_id,priority:1;index:idx_pipeline_executions_user_is_deleted,priority:1" json:"user_id"`
	PipelineID        string         `gorm:"column:pipeline_id;type:uuid;not null;index:idx_pipeline_executions_pipeline_id,priority:1" json:"pipeline_id"`
	Status            *string        `gorm:"column:status;type:character varying(50);not null;index:idx_pipeline_executions_status,priority:1;index:idx_pipeline_executions_status_created,priority:1;default:pending" json:"status"`
	CurrentStageIndex *int32         `gorm:"column:current_stage_index;type:integer" json:"current_stage_index"`
	Input             string         `gorm:"column:input;type:jsonb;not null" json:"input"`
	Output            string         `gorm:"column:output;type:jsonb;not null" json:"output"`
	IsDeleted         bool           `gorm:"column:is_deleted;type:boolean;not null;index:idx_pipeline_executions_is_deleted,priority:1;index:idx_pipeline_executions_user_is_deleted,priority:2" json:"is_deleted"`
	StartedAt         *time.Time     `gorm:"column:started_at;type:timestamp with time zone" json:"started_at"`
	CompletedAt       *time.Time     `gorm:"column:completed_at;type:timestamp with time zone" json:"completed_at"`
	CreatedAt         *time.Time     `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_pipeline_executions_created_at,priority:1;index:idx_pipeline_executions_status_created,priority:2;default:now()" json:"created_at"`
	UpdatedAt         *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index:idx_pipeline_executions_deleted_at,priority:1" json:"deleted_at"`
}

// TableName PipelineExecution's table name
func (*PipelineExecution) TableName() string {
	return TableNamePipelineExecution
}
