// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSession = "sessions"

// Session mapped from table <sessions>
type Session struct {
	ID            *string        `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	UserID        string         `gorm:"column:user_id;type:uuid;not null;index:idx_sessions_user_id,priority:1;index:idx_sessions_user_is_deleted,priority:1" json:"user_id"`
	Title         *string        `gorm:"column:title;type:character varying(255)" json:"title"`
	Summary       *string        `gorm:"column:summary;type:text" json:"summary"`
	Status        *string        `gorm:"column:status;type:character varying(50);not null;index:idx_sessions_status,priority:1;default:active" json:"status"`
	Metadata      *string        `gorm:"column:metadata;type:jsonb;not null;default:{}" json:"metadata"`
	IsDeleted     bool           `gorm:"column:is_deleted;type:boolean;not null;index:idx_sessions_user_is_deleted,priority:2;index:idx_sessions_is_deleted,priority:1" json:"is_deleted"`
	LastMessageAt *time.Time     `gorm:"column:last_message_at;type:timestamp with time zone;index:idx_sessions_last_message_at,priority:1" json:"last_message_at"`
	CreatedAt     *time.Time     `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_sessions_created_at,priority:1;default:now()" json:"created_at"`
	UpdatedAt     *time.Time     `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index:idx_sessions_deleted_at,priority:1" json:"deleted_at"`
}

// TableName Session's table name
func (*Session) TableName() string {
	return TableNameSession
}
